package com.demo.webapp.views;

import java.io.ByteArrayOutputStream;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.servlet.view.AbstractView;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.PageSize;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfWriter;

/**
 * 
 * @author Yusdel Morales
 * Parent class for generating PDF files
 * TODO Return JSON/XML/Excel/PDF/CSV data
 */

public abstract class MyAbstractPdfView extends AbstractView
{
	//Rectangle = to specify the type and size of the PDF page!
	protected Rectangle pageSize = PageSize.A4;
	//page orientation (landscape or portrait)
	protected boolean isLandScape = true;
	
	//page margins
	protected float mrgLeft = 10;
	protected float mrgRight = 10;
	protected float mrgTop = 10;
	protected float mrgBottom = 10;
	
	public MyAbstractPdfView()
	{
		//type of file generated by this abstract class
		setContentType("application/pdf");
	}
	
	@Override
	protected boolean generatesDownloadContent()
	{
		// self-download
		return true;
	}
	
	@Override
	protected final void renderMergedOutputModel(Map<String, Object> model, HttpServletRequest request,
			HttpServletResponse response) throws Exception
	{

		// IE workaround: write into byte array first.
		ByteArrayOutputStream baos = createTemporaryOutputStream();

		//orientation
		pageSize = (isLandScape) ? pageSize.rotate() : pageSize;
		
		// document preferences
		Document document = new Document(pageSize, mrgLeft, mrgRight, mrgTop, mrgBottom);
		
		PdfWriter writer = PdfWriter.getInstance(document, baos);
		prepareWriter(model, writer, request);
		buildPdfMetadata(model, document, request);

		// Creation of the PDF file
		document.open();
		buildPdfDocument(model, document, writer, request, response);
		document.close();

		// Flush to HTTP response.
		writeToResponse(response, baos);
	}
	
	protected void prepareWriter(Map<String, Object> model, PdfWriter writer, HttpServletRequest request)
			throws DocumentException
	{
		writer.setViewerPreferences(getViewerPreferences());
	}
	
	protected int getViewerPreferences()
	{
		// set layout single page and allow file printing 
		return  PdfWriter.ALLOW_PRINTING | PdfWriter.PageLayoutSinglePage;
	}
	
	protected void buildPdfMetadata(Map<String, Object> model, Document document, HttpServletRequest request)
	{
	}
	
	protected abstract void buildPdfDocument(Map<String, Object> model, Document document, PdfWriter writer,
			HttpServletRequest request, HttpServletResponse response) throws Exception;
}
